src/FAC.Web/Controllers/TrainingController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FAC.Web.Controllers
{
    
    public class TrainingController : Controller
    {
        // GET: Training
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult IELTS()
        {
            ViewBag.CurrentTraining = "IELTS";
            return View();
        }
        public ActionResult PTE()
        {
            ViewBag.CurrentTraining = "PTE";
            return View();
        }
        public ActionResult TOEFL()
        {
            ViewBag.CurrentTraining = "TOEFL";
            return View();
        }
        public ActionResult EnglishSpoken()
        {
            ViewBag.CurrentTraining = "EnglishSpoken";
            return View();
        }
    }
}

src/FAC.Web/Views/Training/EnglishSpoken.cshtml
@{
    ViewBag.Title = "EnglishSpoken";
}

<!-- Start main-content -->
<section class="page-title" style="background-image: url(../../media/images/background/page-title.jpg);">
    <div class="auto-container">
        <div class="title-outer">
            <h1 class="title">English Spoken</h1>
            <ul class="page-breadcrumb">
                <li>@Html.ActionLink("Home", "Index", "Home", new { area = "" }, new { @class = "" })</li>
                <li>@Html.ActionLink("Courses", "Index", "Training", new { area = "" }, new { @class = "" })</li>
                <li>English Spoken</li>
            </ul>
        </div>
    </div>
</section>
<!-- end main-content -->
<!--Start courses Details-->
<section class="course-details">
    <div class="container">
        <div class="row flex-xl-row-reverse">
            <!--Start courses Details Content-->
            <div class="col-xl-8 col-lg-8">
                <div class="courses-details__content">
                    <img src="~/media/images/resource/course-details.jpg" alt="" />
                    <h2 class="mt-4">English Spoken Overview</h2>
                    <p>
                        Speaking skills are defined as skills which allow us to communicate effectively.These skills give us the ability to convey information verbally and in way that the listener can understand.
                    </p>
                    <div class="content mt-40">
                        <div class="text">
                            <h3>What You Will Learn?</h3>
                            <p>In this English course which is taught by experts who have years of teaching experience. This spoken English course will teach you about pronunciation, responses, basic Grammar, telephonic English, public speech, vocabulary and much more.</p>
                        </div>
                        <div class="row mt-30">
                            <!-- Features Block Two -->
                            <div class="feature-block col-lg-6 col-md-6 col-sm-12">
                                <div class="inner-box">
                                    <i class="icon flaticon-interview"></i>
                                    <span class="cat">The eget mattis</span>
                                    <h6 class="title"><a href="#">Direct Interviews</a></h6>
                                </div>
                            </div>

                            <!-- Feature Block -->
                            <div class="feature-block col-lg-6 col-md-6 col-sm-12">
                                <div class="inner-box">
                                    <div class="content">
                                        <i class="icon flaticon-low-cost"></i>
                                        <span class="cat">The eget mattis</span>
                                        <h6 class="title"><a href="#">Cost Effective</a></h6>
                                    </div>
                                </div>
                            </div>

                            <!-- Features Block Two -->
                            <div class="feature-block col-lg-6 col-md-6 col-sm-12">
                                <div class="inner-box">
                                    <div class="content">
                                        <i class="icon flaticon-loyalty"></i>
                                        <span class="cat">The eget mattis</span>
                                        <h6 class="title"><a href="#">Trusted Customers</a></h6>
                                    </div>
                                </div>
                            </div>

                            <!-- Feature Block -->
                            <div class="feature-block col-lg-6 col-md-6 col-sm-12">
                                <div class="inner-box">
                                    <div class="content">
                                        <i class="icon flaticon-online-support"></i>
                                        <span class="cat">The eget mattis</span>
                                        <h6 class="title"><a href="#">Support Team</a></h6>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class=" mt-25">
                        <h3>Frequently Asked Question</h3>
                      @*  <p>Lorem ipsum is simply free text used by copytyping refreshing. Neque porro est qui dolorem ipsum quia quaed inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.</p>*@
                    <ul class="accordion-box wow fadeInRight">
                        <!--Block-->
                        <li class="accordion block active-block">
                            <div class="acc-btn active">
                                How can I expand my vocabulary?
                                <div class="icon fa fa-plus"></div>
                            </div>
                            <div class="acc-content current">
                                <div class="content">
                                    <div class="text">Learning vocabulary the old way requires time and dedication and is anything but inspiring. Trying to memorize a vocabulary list is as boring as it is ineffective, so forget about your school days and start improving your English more efficiently. The first thing to remember is that every step matters. If it is bringing you closer to your goal, it counts..</div>
                                </div>
                            </div>
                        </li>
                        <!--Block-->
                        <li class="accordion block">
                            <div class="acc-btn">
                                How can I improve my accent in English?
                                <div class="icon fa fa-plus"></div>
                            </div>
                            <div class="acc-content">
                                <div class="content">
                                    <div class="text">
                                        You actually don't need to get rid of your accent. We all have one personality. As long as it is clearly understood and you don't face misunderstandings. You can improve your accent by mimicking your favorite actor or actress. Shadowing, as we explained ,we can also help you improve your accent in English. You can also learn how to pronounce difficult sounds
                                    </div>
                                </div>
                            </div>
                        </li>
                        <!--Block-->
                        <li class="accordion block">
                            <div class="acc-btn">
                                How can I link my ideas together to sound more like a native speaker?
                                <div class="icon fa fa-plus"></div>
                            </div>
                            <div class="acc-content">
                                <div class="content">
                                    <div class="text">
                                        .One of the tricks to sound more like a native speaker is to use linkers or connectors. These will connect your ideas together and you will seem much more fluent and in control.  Here's the example with connectors, "While Company B kept focusing on the negatives, they seemed interested in the product. That's why we were not completely sure if we would manage to get this client. However, we kept insisting and providing them with solutions, and as a result, they decided to close the deal"
                                    </div>
                                </div>
                            </div>
                        </li>
                    </ul>
                    </div>
                </div>
            </div>
            <!--End courses Details Content-->
            <!--Start courses Details Sidebar-->
            <div class="col-xl-4 col-lg-4">
                <div class="course-sidebar">
                    <ul class="course-details-info">
                        <li class="course-details-info-link">
                            <span class="course-details-info-icon"><i class="far fa-clock"></i></span>
                            Durations: <span>10 hours</span>
                        </li>
                        <li class="course-details-info-link">
                            <span class="course-details-info-icon"><i class="far fa-folder-open"></i></span>
                            Lectures: <span>15</span>
                        </li>
                        <li class="course-details-info-link">
                            <span class="course-details-info-icon"><i class="far fa-user-circle"></i></span>
                            Students: <span>Max 50</span>
                        </li>
                        <li class="course-details-info-link">
                            <span class="course-details-info-icon"><i class="far fa-flag"></i></span>
                            Skill Level: <span>Advanced</span>
                        </li>
                        <li class="course-details-info-link">
                            <span class="course-details-info-icon"><i class="far fa-bell"></i></span>
                            Language: <span>English</span>
                        </li>
                    </ul>

                    <div class="course-details-price">
                        <p class="course-details-price-text">Course price</p>
                        <p class="course-details-price-amount">$18.00</p>
                        <a href="page-course.html" class="theme-btn btn-style-one course-details-price-btn"><span class="btn-title">Buy This Course</span></a>
                    </div>

                    <div class="latest-course mb-30">
                        <h4 class="latest-course-title mb-30">New Courses</h4>
                        <div class="latest-course-item">
                            <div class="latest-course-img">
                                <img src="~/media/images/resource/gallery-1.jpg" alt="">
                            </div>
                            <div class="latest-course-content">
                                <a class="latest-course-author" href="#">by <span>Advanced</span></a>
                                <h5><a href="page-course-details.html">TOEFL Coaching</a></h5>
                                <div class="latest-course-stars">
                                    <i class="fas fa-star"></i>
                                    <i class="fas fa-star"></i>
                                    <i class="fas fa-star"></i>
                                    <i class="fas fa-star"></i>
                                    <i class="fas fa-star"></i>
                                    <span>4.8</span>
                                </div>
                            </div>
                        </div>
                        <div class="latest-course-item">
                            <div class="latest-course-img">
                                <img src="~/media/images/resource/gallery-2.jpg" alt="">
                            </div>
                            <div class="latest-course-content">
                                <a class="latest-course-author" href="#">by <span>Advanced</span></a>
                                <h5><a href="page-course-details.html">Citizenship Test</a></h5>
                                <div class="latest-course-stars">
                                    <i class="fas fa-star"></i>
                                    <i class="fas fa-star"></i>
                                    <i class="fas fa-star"></i>
                                    <i class="fas fa-star"></i>
                                    <i class="fas fa-star"></i>
                                    <span>5.0</span>
                                </div>
                            </div>
                        </div>
                        <div class="latest-course-item">
                            <div class="latest-course-img">
                                <img src="~/media/images/resource/gallery-3.jpg" alt="">
                            </div>
                            <div class="latest-course-content">
                                <a class="latest-course-author" href="#">by <span>Advanced</span></a>
                                <h5><a href="page-course-details.html">PTE Coaching</a></h5>
                                <div class="latest-course-stars">
                                    <i class="fas fa-star"></i>
                                    <i class="fas fa-star"></i>
                                    <i class="fas fa-star"></i>
                                    <i class="fas fa-star"></i>
                                    <i class="fas fa-star"></i>
                                    <span>4.9</span>
                                </div>
                            </div>
                        </div>
                    </div>

                </div>
            </div>
            <!--End courses Details Sidebar-->
        </div>
    </div>
</section>
<!--End courses Details-->

src/FAC.Web/Views/Training/IELTS.cshtml
@{
    ViewBag.Title = "IELTS";
}





<!-- Start main-content -->
<section class="page-title" style="background-image: url(../../media/images/background/page-title.jpg);">
    <div class="auto-container">
        <div class="title-outer">
            <h1 class="title">IELTS</h1>
            <ul class="page-breadcrumb">
                <li>@Html.ActionLink("Home", "Index", "Home", new { area = "" }, new { @class = "" })</li>
                <li>@Html.ActionLink("Courses", "Index", "Training", new { area = "" }, new { @class = "" })</li>
                <li>IELTS</li>
            </ul>
        </div>
    </div>
</section>
<!-- end main-content -->

<!--Start courses Details-->

<section class="course-details">
    <div class="container">
        <div class="row flex-xl-row-reverse">


            <!--Start courses Details Content-->
            <div class="col-xl-8 col-lg-8">

                <div class="courses-details__content">
                    <img src="~/media/images/resource/course-details.jpg" alt="" />
                    <h2 class="mt-4">IELTS Overview</h2>
                    <p>
                      The International English Language Testing System (IELTS) is designed to help you work, study or migrate to a country where English is the native language. This includes countries such as Australia, Canada, New Zealand, the UK and USA.
                    </p>
                    <p>   
                      Your ability to listen, read, write and speak in English will be assessed during the test. IELTS is graded on a scale of 1-9.
                    </p>
                    <p>
                      IELTS, the International English Language Testing System, is designed to assess the language ability of candidates who want to study or work where English is the language of communication. It is jointly managed by The British Council and IDP Education Pty Ltd, and was established in 1989. IELTS is widely accepted by British, Canadian, New Zealand, Australian and South African Universities as also over 2,000 Universities in The United States. It is also a mandatory prerequisite for immigration to Australia and Canada.
                    </p>
                    <div class="content mt-40">
                        <div class="text">
                            <h3>What You Will Learn?</h3>
                              <p>The IELTS Academic.</p>
                               <p> Focuses on English reading, writing, listening and speaking for those wanting to study at university or in an academic environment. Many students hoping to study overseas in an English speaking country take our IELTS course.
                            </p>
                        </div>
                        <div class="row mt-30">




                            <!-- Features Block Two -->
                            <div class="feature-block col-lg-6 col-md-6 col-sm-12">

                                <div class="inner-box">
                                    <i class="icon flaticon-interview"></i>
                                    <span class="cat">The eget mattis</span>
                                    <h6 class="title"><a href="#">Direct Interviews</a></h6>
                                </div>
                            </div>

                            <!-- Feature Block -->
                            <div class="feature-block col-lg-6 col-md-6 col-sm-12">
                                <div class="inner-box">
                                    <div class="content">
                                        <i class="icon flaticon-low-cost"></i>
                                        <span class="cat">The eget mattis</span>
                                        <h6 class="title"><a href="#">Cost Effective</a></h6>
                                    </div>
                                </div>
                            </div>

                            <!-- Features Block Two -->
                            <div class="feature-block col-lg-6 col-md-6 col-sm-12">
                                <div class="inner-box">
                                    <div class="content">
                                        <i class="icon flaticon-loyalty"></i>
                                        <span class="cat">The eget mattis</span>
                                        <h6 class="title"><a href="#">Trusted Customers</a></h6>
                                    </div>
                                </div>
                            </div>

                            <!-- Feature Block -->
                            <div class="feature-block col-lg-6 col-md-6 col-sm-12">
                                <div class="inner-box">
                                    <div class="content">
                                        <i class="icon flaticon-online-support"></i>
                                        <span class="cat">The eget mattis</span>
                                        <h6 class="title"><a href="#">Support Team</a></h6>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class=" mt-25">
                        <h3>Frequently Asked Question</h3>
                       
                        <ul class="accordion-box wow fadeInRight">
                            <!--Block-->
                            <li class="accordion block active-block">
                                <div class="acc-btn active">
                                    How much does it cost?
                                    <div class="icon fa fa-plus"></div>
                                </div>
                                <div class="acc-content current">
                                    <div class="content">
                                        <div class="text">IELTS test fees vary from country to country. Your IDP Education student counsellor will advise the test fee for your country in your local currency, or contact your nearest test centre. The IELTS test fee is the same for both versions of the test (Academic and General ).</div>
                                    </div>
                                </div>
                            </li>
                            <!--Block-->
                            <li class="accordion block">
                                <div class="acc-btn">
                                    What is the Speaking test?
                                    <div class="icon fa fa-plus"></div>
                                </div>
                                <div class="acc-content">
                                    <div class="content">
                                        <div class="text">The Speaking test is a discussion over 11-14 minutes with a certified and highly qualified IELTS Examiner. It is made up of three sections and is recorded.</div>
                                    </div>
                                </div>
                            </li>
                            <!--Block-->
                            <li class="accordion block">
                                <div class="acc-btn">
                                    Who sets the 'pass mark' for the IELTS test?
                                    <div class="icon fa fa-plus"></div>
                                </div>
                                <div class="acc-content">
                                    <div class="content">
                                        <div class="text">There is no pass or fail in IELTS. Scores are graded on the 9-band system. Each educational institution or organisation sets its own minimum IELTS scores to meet its individual requirements.</div>
                                    </div>
                                </div>
                            </li>
                        </ul>
                    </div>

                 




                </div>
            </div>
            <!--End courses Details Content-->
            <!--Start courses Details Sidebar-->
            <div class="col-xl-4 col-lg-4">
                <div class="course-sidebar">
                    <ul class="course-details-info">
                        <li class="course-details-info-link">
                            <span class="course-details-info-icon"><i class="far fa-clock"></i></span>
                            Durations: <span>10 hours</span>
                        </li>
                        <li class="course-details-info-link">
                            <span class="course-details-info-icon"><i class="far fa-folder-open"></i></span>
                            Lectures: <span>15</span>
                        </li>
                        <li class="course-details-info-link">
                            <span class="course-details-info-icon"><i class="far fa-user-circle"></i></span>
                            Students: <span>Max 50</span>
                        </li>
                        <li class="course-details-info-link">
                            <span class="course-details-info-icon"><i class="far fa-flag"></i></span>
                            Skill Level: <span>Advanced</span>
                        </li>
                        <li class="course-details-info-link">
                            <span class="course-details-info-icon"><i class="far fa-bell"></i></span>
                            Language: <span>English</span>
                        </li>
                    </ul>

                    <div class="course-details-price">
                        <p class="course-details-price-text">Course price</p>
                        <p class="course-details-price-amount">$18.00</p>
                        <a href="page-course.html" class="theme-btn btn-style-one course-details-price-btn"><span class="btn-title">Buy This Course</span></a>
                    </div>

                    <div class="latest-course mb-30">
                        <h4 class="latest-course-title mb-30">New Courses</h4>
                        <div class="latest-course-item">
                            <div class="latest-course-img">
                                <img src="~/media/images/resource/gallery-1.jpg" alt="">
                            </div>
                            <div class="latest-course-content">
                                <a class="latest-course-author" href="#">by <span>Advanced</span></a>
                                <h5><a href="page-course-details.html">TOEFL Coaching</a></h5>
                                <div class="latest-course-stars">
                                    <i class="fas fa-star"></i>
                                    <i class="fas fa-star"></i>
                                    <i class="fas fa-star"></i>
                                    <i class="fas fa-star"></i>
                                    <i class="fas fa-star"></i>
                                    <span>4.8</span>
                                </div>
                            </div>
                        </div>
                        <div class="latest-course-item">
                            <div class="latest-course-img">
                                <img src="~/media/images/resource/gallery-2.jpg" alt="">
                            </div>
                            <div class="latest-course-content">
                                <a class="latest-course-author" href="#">by <span>Advanced</span></a>
                                <h5><a href="page-course-details.html">Citizenship Test</a></h5>
                                <div class="latest-course-stars">
                                    <i class="fas fa-star"></i>
                                    <i class="fas fa-star"></i>
                                    <i class="fas fa-star"></i>
                                    <i class="fas fa-star"></i>
                                    <i class="fas fa-star"></i>
                                    <span>5.0</span>
                                </div>
                            </div>
                        </div>
                        <div class="latest-course-item">
                            <div class="latest-course-img">
                                <img src="~/media/images/resource/gallery-3.jpg" alt="">
                            </div>
                            <div class="latest-course-content">
                                <a class="latest-course-author" href="#">by <span>Advanced</span></a>
                                <h5><a href="page-course-details.html">PTE Coaching</a></h5>
                                <div class="latest-course-stars">
                                    <i class="fas fa-star"></i>
                                    <i class="fas fa-star"></i>
                                    <i class="fas fa-star"></i>
                                    <i class="fas fa-star"></i>
                                    <i class="fas fa-star"></i>
                                    <span>4.9</span>
                                </div>
                            </div>
                        </div>
                    </div>

                </div>
            </div>
            <!--End courses Details Sidebar-->
        </div>
    </div>
</section>
<!--End courses Details-->